## BUILD A DOCKER IMAGE BASED ON PYTHON 3.12 SLIM VERSION
FROM python:3.12-slim


## UPDATE DOCKER BASE IMAGE (TREAT THIS LIKE A VIRTUAL MACHINE)
RUN apt-get update


##  MAKE DATA DIRECTORIES
RUN mkdir -p /data/outputs/
RUN mkdir -p /data/inputs/
ENV DATA_PATH_MODE=docker


##  MOVE INPUT DATA DIRECTORY
#  TESTING ONLY (DOCKER DESKTOP) >>>>>>
COPY --from=inputs / /data/inputs/
COPY .env ./home/
#  TESTING ONLY (DOCKER DESKTOP) <<<<<<


##  MOVE PYTHON FILES TO CONTAINER ROOT (`docker_entrypoint.py`)
RUN mkdir -p /home/dres/
COPY *.py ./home/
COPY dres/ ./home/dres/


##  INSTALL ALL PYTHON DEPENDENCIES USING `pyproject.toml` (PIP INSTALL)
COPY pyproject.toml ./home/
RUN pip install ./home


##  RUN MODEL
CMD ["python", "./home/docker_entrypoint.py"]